## LT会で話すこと
### テーマは「RUNTEQ生活を通して、学習において大切にしていること・モチベ維持するコツ！」
### 自分が話せそうなもの
- 呼吸法
- openworship
- 読んだ書籍のアウトプット()

---------------------

元々のvisit project_task_path(project, task)から今回の形に変更したことについて「URLヘルパーメソッド、第一引数、第二引数」などの単語を踏まえて説明することは可能でしょうか。

また以下それぞれの形式で記載した際に、何が問題になるのかも簡単に説明をお願いしたいです。

project_task_path(project, task)と記載した場合
project_task_path(task, project)と記載した場合

-----------------------

project_task_pathとは、あるprojectに紐づいたtaskの詳細にアクセスするURLヘルパーメソッドです。

rails routesコマンドを打つと以下のように表示されます
`project_task GET    /projects/:project_id/tasks/:id`

第一引数に指定したいprojectを、第二引数に指定したいtaskを指定することで、以下のようにあるprojectに紐づいたtaskの詳細にアクセスできます。

```
(byebug) project_task_path(task.project, task)
"/projects/1/tasks/1"
```

元々はテストデータを作成する際、projectのテストデータのidをtaskのテストデータに直接代入していました。そのためproject_task_pathの引数に指定しているprojectとtaskには関連がありました。

しかし、ファクトリファイルで関連を定義してテストデータを作成する場合
URLヘルパーメソッドのproject_task_pathに指定しているprojectとtaskとの間に関連がなくなることに気がつきました。

```
(byebug) task
#<Task id: 1, title: "Task", status: "doing", deadline: "2019-10-28 15:00:00", completion_date: nil, description: nil, project_id: 1, created_at: "2021-10-13 11:37:34", updated_at: "2021-10-13 11:37:34">

(byebug) project
#<Project id: 2, name: "nemo", status: "todo", release_date: "2019-01-22", created_at: "2021-10-13 11:37:56", updated_at: "2021-10-13
```
なので、project_task_path(project, task)と記載した場合
taskと紐づいていないprojectが選ばれ、そこにはtaskがないためエラーになります。

その問題を解決するためにproject_task_path(task.project, task)と記載して、projectとtaskとの間に関連を持たせることであるprojectに紐づいたtaskの詳細にアクセスすることができます。

project_task_path(task, project)と記載した場合は単純にエラーになります。

ーーーーーーーーーーーーーーーーー
### 今回の形に変更した理由

taskのファクトリファイルでprojectとの関連を定義してテストデータを作成するために今回の形になりました。

元々はテストデータを作成する際、letで作成したprojectのテストデータのidをtaskのテストデータに直接代入していました。そのためproject_task_pathの引数に指定しているprojectとtaskには関連がありました。

しかし、taskのファクトリファイルで関連を定義してテストデータを作成する場合
project_task_path(project, task)にアクセスしようとすると、エラーが出てしまいました。

原因は、URLヘルパーメソッドのproject_task_pathにおいて、第一引数に指定していたprojectと、第二引数に指定していたtaskとの間に関連がなくなったため、projectに紐づいたtaskが存在しないのでエラーになるようです。

デバックして確認しました

```
describe 'Task詳細' do
   42:     context '正常系' do
   43:       fit 'Taskが表示されること' do
   44:         byebug
=> 45:         visit project_task_path(task.project, task)
```

```
(byebug) project
#<Project id: 1, name: "qui", status: "todo", release_date: "2019-03-27", created_at: "2021-10-15 03:47:44", updated_at: "2021-10-15 03:47:44">

byebug) task
#<Task id: 1, title: "Task", status: "doing", deadline: "2019-12-17 15:00:00", completion_date: nil, description: nil, project_id: 2, created_at: "2021-10-15 03:47:51", updated_at: "2021-10-15 03:47:51">

(byebug) task.project
#<Project id: 2, name: "est", status: "doing", release_date: "2019-11-26", created_at: "2021-10-15 03:47:51", updated_at: "2021-10-15 03:47:51">
```
上記を見る限り
- taskにprojectは紐づいてない
- taskとtask.projectは紐づいている
- projectとtask.projectは別物である
ということがわかりました。

原因を調査すると、Factrybotにおけるアソシエーションは「関連するデータを一緒に作成してくれるメソッド」だということがわかりました
[【FactoryBot】associationの使い方 \- Qiita](https://qiita.com/Ryoga_aoym/items/741c57e266a9d811a2d4#association%E3%81%A8%E3%81%AF)

task.projectは、taskのテストデータを作成した時に同時に作成されるものです。このデータはtaskと関連があります

letで定義されたprojectは、呼び出された時に作成されるテストデータです。これはtaskと関連がありません

そうすると、project_task_path(project, task)にアクセスしようとすると、第一引数に指定したprojectに紐づいたtaskデータがないためエラーになります。

そのため、エラーを解消するためにproject_task_path(task.project, task)という形となりました。

### project_task_path(project, task)と記載した場合
先ほどご説明した通り、projectとtaskに関連がないためエラーになります。

### project_task_path(task, project)と記載した場合
このようなエラーが出ました
```
Failure/Error: @task = @project.tasks.find(params[:id])
     
     ActiveRecord::RecordNotFound:
       Couldn't find Task with 'id'=2 [WHERE "tasks"."project_id" = ?]
```
idが2のtaskが存在しないようです。
デバッグして見ました
```
   41:   describe 'Task詳細' do
   42:     context '正常系' do
   43:       fit 'Taskが表示されること' do
   44:         byebug
=> 45:         visit project_task_path(task, project)
```
```
(byebug) project_task_path(task, project)
"/projects/1/tasks/2"

(byebug) task
#<Task id: 1, title: "Task", status: "doing", deadline: "2019-12-16 15:00:00", completion_date: nil, description: nil, project_id: 1, created_at: 
```

これはなぜ起こるかというと、
projectにtaskが紐づいているのであって、taskにprojectが紐づいているわけではないのでエラーになるということだと思います。

ルーティングを見てみるとわかりやすいと思いました

・rspec_app_exam/config/routes.rb
```
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
```
このようにprojectのリソースの中にtaskのリソースを定義しているのでproject_task_pathというヘルパーメソッドが使えます。

project_task_path(task, project)はこのネストの上下関係を逆にしてしまっているのでエラーになります。